# Copyleft (c) by Ivan D 2020
#-------------------------------------------------------------
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name  : Ivan-cluster1
  region: us-east-2

#vpc

nodeGroups:
 - name           : w-node-group-1
   instanceType   : t2.micro
   desiredCapacity: 1
 - name           : w-node-group-2
   instanceType   : t2.micro
   desiredCapacity: 1
